### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ferigis** [poanetwork/poa-netstats-agent#28]
All the commits related with documentation must be reference this ticket.

- [ ] How to create your own Collector Plugin
- [ ] How to create your own Transfer Plugin
- [ ] How to build, pack and start the Agent

**Comment by Dzol** [comment]
@ferigis Is there something more we want to do on this front or shall we close this ticket following the references above?

**Comment by ferigis** [comment]
@Dzol I think we are done with it. We can close it. If a more detailed doc is needed in future we will open a new one
